import React from 'react';
import ReactDOM from 'react-dom/client';
import { AlertTriangle, ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ExternalLink, FileText, GraduationCap, HelpCircle, Landmark, ListChecks, MapPin, Route, School, ShieldCheck } from 'lucide-react';

const steps = ['確認招生管道：高級中等學校免試入學、五專優先免試入學，或其他招生管道。','下載並詳讀 115 學年度所屬管道的簡章與時程表，核對報名、選填、放榜及報到日期。','逐一蒐集校科資料：課程、特色、交通、住宿、學費、實習與未來升學或就業方向。','向國中輔導室或註冊組確認多元學習表現、比序資料與校內作業期限。','登入系統後，核對個人資料與可選填校科，再依真實就讀意願排序。','在截止前再次檢查，完成系統要求的確認或送出流程，並保存志願表或收據。'];
const rows = [['辦理範圍','依各就學區分別辦理','全國一區辦理'],['志願選填','依各就學區簡章與系統規定','不限地區、學校、科組，最多 30 個志願'],['分發依據','依該就學區簡章的比序規定','依比序總積分、同分比序與志願序統一分發'],['最重要資料','所屬就學區的招生簡章與公告','五專優先免試入學招生簡章與系統公告']];

function ArticlePage() { return <div className="min-h-screen bg-slate-50 text-slate-800 selection:bg-indigo-600 selection:text-white">
  <div className="fixed inset-0 -z-10 overflow-hidden"><div className="absolute -top-48 left-1/4 h-[34rem] w-[34rem] rounded-full bg-indigo-300/20 blur-3xl" /><div className="absolute top-80 -right-36 h-[28rem] w-[28rem] rounded-full bg-cyan-200/25 blur-3xl" /></div>
  <nav className="sticky top-0 z-30 border-b border-white/60 bg-white/85 px-4 py-3 backdrop-blur-xl sm:px-6"><div className="mx-auto flex max-w-6xl items-center justify-between"><a href="./" className="flex items-center gap-3"><span className="rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 p-2 text-white"><GraduationCap className="h-5 w-5" /></span><span className="font-bold tracking-tight text-slate-800">教育會考志願選填資訊</span></a><a href="./" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-slate-600 hover:bg-indigo-50 hover:text-indigo-700"><ArrowLeft className="h-4 w-4" />回首頁</a></div></nav>
  <main className="mx-auto max-w-6xl px-4 pb-20 pt-12 sm:px-6"><header className="overflow-hidden rounded-[2rem] bg-slate-900 px-7 py-12 text-white shadow-2xl shadow-slate-900/15 sm:px-12 md:py-16"><p className="inline-flex items-center gap-2 rounded-full border border-indigo-300/25 bg-indigo-400/15 px-3 py-1.5 text-xs font-bold text-indigo-100"><BookOpen className="h-3.5 w-3.5" />115 學年度適用閱讀指引</p><h1 className="mt-6 max-w-4xl text-4xl font-black tracking-tight sm:text-5xl">志願選填完整說明：<br className="hidden sm:block" />從準備、排序到送出的每一步</h1><p className="mt-6 max-w-3xl text-base font-medium leading-8 text-slate-300">志願選填不是猜分數，而是根據招生規則、個人條件與真實意願作出排序。本文整理通用流程；資格、比序、名額與日期請以當年度招生簡章及官方系統公告為準。</p></header>
  <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_18rem]"><article className="space-y-10"><section className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><div className="flex items-center gap-3"><span className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600"><Route className="h-5 w-5" /></span><div><p className="text-xs font-bold tracking-wider text-indigo-600">FIRST, CHOOSE A PATH</p><h2 className="text-2xl font-black text-slate-900">先分清楚：你要填的是哪一種志願？</h2></div></div><p className="mt-6 leading-8 text-slate-600">國中畢業後的升學管道不只一種。目標是一般高中、技術型高中或綜合高中，通常要看<strong className="text-slate-800">所屬就學區的高級中等學校免試入學</strong>；目標是五專，則要另外確認五專完全免試、優先免試或北、中、南區聯合免試等管道。不同管道的資格、報名方式、時程與比序方式都可能不同，不能互相套用。</p><div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200"><table className="w-full min-w-[590px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-4 font-bold">比較項目</th><th className="px-5 py-4 font-bold">高級中等學校免試入學</th><th className="px-5 py-4 font-bold">五專優先免試入學</th></tr></thead><tbody>{rows.map(row => <tr key={row[0]} className="border-t border-slate-100"><th className="px-5 py-4 font-bold text-slate-800">{row[0]}</th><td className="px-5 py-4 leading-6 text-slate-600">{row[1]}</td><td className="px-5 py-4 leading-6 text-slate-600">{row[2]}</td></tr>)}</tbody></table></div></section>
  <section><div className="mb-5"><p className="text-sm font-bold text-indigo-600">STEP BY STEP</p><h2 className="mt-1 text-3xl font-black tracking-tight text-slate-900">選填前到送出後的完整流程</h2></div><div className="space-y-4">{steps.map((item, index) => <div key={item} className="flex gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-indigo-600 text-sm font-black text-white">{index + 1}</span><p className="pt-1 text-sm font-medium leading-7 text-slate-600">{item}</p></div>)}</div></section>
  <section className="rounded-3xl border border-amber-200 bg-amber-50 p-7 sm:p-9"><div className="flex items-center gap-3 text-amber-800"><AlertTriangle className="h-6 w-6" /><h2 className="text-2xl font-black">志願排序的核心原則</h2></div><p className="mt-5 leading-8 text-slate-700">把<strong>最想讀、即使錄取也願意去就讀</strong>的校科排在前面。不要只因為聽說分數高或低而把真正想讀的選項往後放。志願序本身可能是比序或分發過程的一環；更重要的是，統一分發會依規則在你可分發的選項中處理志願，因此排序應反映真實意願。</p><ul className="mt-5 space-y-3 text-sm font-medium leading-6 text-slate-700"><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-amber-700" />以「我是否願意就讀」決定先後，而非只看校名或他人的排序。</li><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-amber-700" />同一校不同科別的課程與未來進路可能差異很大，應逐科確認。</li><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-amber-700" />不要只準備少量志願；可填數量與策略請依所屬管道簡章規定。</li></ul></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><div className="flex items-center gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-600"><ListChecks className="h-5 w-5" /></span><h2 className="text-2xl font-black text-slate-900">每一個校科，都請檢查這些條件</h2></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{['課程內容與專業方向是否符合興趣與能力？','是否有特殊門檻、性別限制或身分條件？','交通時間、住宿需求與家庭支持是否可行？','學費、雜費、實習或設備費等成本是否已了解？','升學、證照、實習與就業方向是否符合期待？','錄取後的報到規則，會不會影響其他已錄取管道？'].map(item => <p key={item} className="flex gap-3 rounded-xl bg-slate-50 p-4 text-sm font-medium leading-6 text-slate-600"><ShieldCheck className="h-5 w-5 shrink-0 text-emerald-600" />{item}</p>)}</div></section>
  <section className="rounded-3xl border border-rose-200 bg-rose-50/70 p-7 sm:p-9"><h2 className="text-2xl font-black text-slate-900">最容易忽略的四件事</h2><ol className="mt-6 space-y-4 text-sm leading-7 text-slate-700"><li><strong>截止時間不等於開始時間：</strong>系統可能在截止當日停止受理，請預留登入、修改與確認時間。</li><li><strong>校內期限可能早於官方期限：</strong>應屆生常須配合國中端資料確認與集體作業，務必詢問學校承辦人。</li><li><strong>名額與簡章可能有更新：</strong>實際招生名額、校科資訊與規則以官方當年度公告為準。</li><li><strong>錄取不等於完成：</strong>錄取後仍可能需要依規定完成報到、放棄或其他程序；逾期處理可能影響權益。</li></ol></section></article>
  <aside className="space-y-5 lg:sticky lg:top-24 lg:self-start"><div className="rounded-3xl border border-indigo-100 bg-indigo-50 p-6"><MapPin className="h-6 w-6 text-indigo-600" /><h2 className="mt-4 font-black text-slate-900">你需要的官方資料</h2><p className="mt-2 text-sm leading-6 text-slate-600">優先查看所屬就學區或招生委員會公告的招生簡章、重要日程與系統說明。</p></div><a href="https://cap.rcpet.edu.tw/" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 text-sm font-bold text-slate-700 shadow-sm transition hover:border-indigo-200 hover:text-indigo-700"><span className="flex items-center gap-3"><Landmark className="h-5 w-5" />國中教育會考官網</span><ExternalLink className="h-4 w-4" /></a><a href="https://www.techadmi.edu.tw/page.php?gid=1028&pid=1077" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 text-sm font-bold text-slate-700 shadow-sm transition hover:border-indigo-200 hover:text-indigo-700"><span className="flex items-center gap-3"><School className="h-5 w-5" />五專優先免試說明</span><ExternalLink className="h-4 w-4" /></a><a href="https://www.techadmi.edu.tw/qa_detail.php?gid=575&nid=591" target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-5 text-sm font-bold text-slate-700 shadow-sm transition hover:border-indigo-200 hover:text-indigo-700"><span className="flex items-center gap-3"><HelpCircle className="h-5 w-5" />五專招生常見問答</span><ExternalLink className="h-4 w-4" /></a><div className="rounded-3xl bg-slate-900 p-6 text-white"><FileText className="h-6 w-6 text-indigo-300" /><h2 className="mt-4 font-black">最後提醒</h2><p className="mt-2 text-sm leading-6 text-slate-300">本文是閱讀與決策指南，不是招生簡章。涉及資格、積分、名額、日期與報到，請一律以當年度正式公告為準。</p><a href="info.html" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-white hover:text-indigo-200">使用說明與 FAQ <ArrowRight className="h-4 w-4" /></a></div></aside></div></main>
</div>; }
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ArticlePage /></React.StrictMode>);
