import React from 'react';
import ReactDOM from 'react-dom/client';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ChevronDown, ExternalLink, GraduationCap, HelpCircle, Lightbulb, Mail, Sparkles } from 'lucide-react';

const faqs = [
  { question: '志願選填前，應該先準備什麼？', answer: '先確認個人免試入學相關資料與時程，整理想就讀的學校與科別，再依序查看各就學區網站公布的簡章、名額與超額比序資訊。' },
  { question: '這個網站可以直接幫我完成選填嗎？', answer: '本頁提供資訊入口與使用指引；實際志願選填仍須前往各就學區的官方系統，並依該系統流程完成。' },
  { question: '忘記帳號或密碼怎麼辦？', answer: '請依官方系統登入頁面的說明進行帳號或密碼查詢；若仍無法處理，請洽就讀國中或所屬就學區承辦單位。' },
  { question: '送出志願後還可以修改嗎？', answer: '可否修改與截止時間會依各就學區規定不同。送出前請再次核對志願順序，並以官方公告的時間與規則為準。' },
  { question: '遇到不確定的規則時該問誰？', answer: '優先詢問學校輔導室、註冊組或導師；涉及系統操作與招生日程時，請直接參考官方網站與各就學區公告。' },
];

const steps = [
  ['確認時程', '先記下報名、選填、繳交資料與放榜等關鍵日期。'],
  ['蒐集資訊', '查看校系特色、名額、比序條件與通勤等實際需求。'],
  ['安排志願', '依興趣、能力與風險分層，排出理想、適合與穩健的選擇。'],
  ['送出前核對', '確認帳號、志願順序與所有欄位，再依官方流程完成送出。'],
];

function InfoPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-800 selection:bg-indigo-500 selection:text-white">
    <div className="fixed inset-0 -z-10 overflow-hidden"><div className="absolute -top-40 left-[15%] h-96 w-96 rounded-full bg-indigo-300/25 blur-3xl" /><div className="absolute top-32 right-[10%] h-80 w-80 rounded-full bg-violet-300/20 blur-3xl" /><div className="absolute inset-0 bg-[linear-gradient(to_right,#64748b0a_1px,transparent_1px),linear-gradient(to_bottom,#64748b0a_1px,transparent_1px)] bg-[size:28px_28px]" /></div>
    <nav className="sticky top-0 z-20 px-4 pt-4 sm:px-6"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between rounded-2xl border border-white/70 bg-white/80 px-5 shadow-sm backdrop-blur-xl sm:px-6"><a href="./" className="group flex items-center gap-3" aria-label="回到首頁"><span className="rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 p-2 text-white shadow-lg shadow-indigo-500/25"><GraduationCap className="h-5 w-5" /></span><span className="font-bold tracking-tight text-slate-800">教育會考志願選填資訊</span></a><a href="./" className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold text-slate-600 transition hover:bg-indigo-50 hover:text-indigo-700"><ArrowLeft className="h-4 w-4" />回首頁</a></div></nav>
    <main className="mx-auto max-w-6xl px-4 pb-20 pt-14 sm:px-6"><section className="grid gap-10 rounded-[2rem] border border-white/80 bg-white/70 p-7 shadow-[0_20px_60px_-30px_rgba(79,70,229,.3)] backdrop-blur-xl md:grid-cols-[1.15fr_.85fr] md:p-12"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1.5 text-xs font-bold tracking-wide text-indigo-700"><Sparkles className="h-3.5 w-3.5" />選填前的實用指南</p><h1 className="text-4xl font-black tracking-tight text-slate-900 sm:text-5xl">使用說明與<br /><span className="bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent">常見問題</span></h1><p className="mt-6 max-w-xl text-base font-medium leading-8 text-slate-600">把重要的選填步驟、注意事項與常見疑問整理在同一頁。需要進一步確認時，請以各就學區官方公告為準。</p><div className="mt-8 flex flex-wrap gap-3"><a href="#faq" className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-slate-900/15 transition hover:bg-indigo-600">查看常見問題 <ArrowRight className="h-4 w-4" /></a><a href="https://cap.rcpet.edu.tw/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700 transition hover:border-indigo-200 hover:text-indigo-700">官方網站 <ExternalLink className="h-4 w-4" /></a></div></div><aside className="rounded-3xl bg-gradient-to-br from-indigo-600 to-violet-700 p-7 text-white shadow-xl shadow-indigo-500/20"><BookOpen className="h-8 w-8 text-indigo-100" /><h2 className="mt-8 text-2xl font-black">開始前，先做這三件事</h2><ol className="mt-6 space-y-4 text-sm font-medium text-indigo-100">{['確認所屬就學區與官方時程。', '備妥帳密與個人相關資料。', '和家長、師長討論志願順序。'].map((item, i) => <li key={item} className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-white/15 text-xs font-black text-white">{i + 1}</span>{item}</li>)}</ol></aside></section>
      <section className="mt-16"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="text-sm font-bold text-indigo-600">HOW TO START</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-900">選填流程，簡單掌握</h2></div><span className="hidden rounded-full bg-white px-4 py-2 text-sm font-bold text-slate-500 shadow-sm sm:block">四個步驟完成準備</span></div><div className="grid gap-4 md:grid-cols-4">{steps.map(([title, description], index) => <article key={title} className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-50 text-sm font-black text-indigo-600">0{index + 1}</span><h3 className="mt-6 font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>)}</div></section>
      <section className="mt-16 grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[2rem] border border-amber-100 bg-amber-50/70 p-8"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-100 text-amber-700"><Lightbulb className="h-5 w-5" /></div><h2 className="mt-6 text-2xl font-black text-slate-900">選填注意事項</h2><ul className="mt-6 space-y-4">{['所有時程與規則以官方公告為準。', '志願送出前，務必再次確認排序。', '遇到問題時，及早向學校師長詢問。', '不要將帳號與密碼提供給他人。'].map(item => <li key={item} className="flex gap-3 text-sm font-medium leading-6 text-slate-600"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" />{item}</li>)}</ul></div><div id="faq" className="scroll-mt-24"><p className="text-sm font-bold text-indigo-600">FAQ</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-900">常見問題</h2><div className="mt-6 space-y-3">{faqs.map((faq, index) => <details key={faq.question} open={index === 0} className="group rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 px-5 py-5 font-bold text-slate-800 marker:content-none"><span>{faq.question}</span><ChevronDown className="h-5 w-5 shrink-0 text-slate-400 transition group-open:rotate-180 group-open:text-indigo-600" /></summary><p className="border-t border-slate-100 px-5 py-4 text-sm font-medium leading-7 text-slate-600">{faq.answer}</p></details>)}</div></div></section>
      <section className="mt-16 rounded-[2rem] bg-slate-900 px-7 py-10 text-center text-white sm:px-12"><HelpCircle className="mx-auto h-7 w-7 text-indigo-300" /><h2 className="mt-4 text-2xl font-black">還有其他問題嗎？</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-300">可先向就讀學校的輔導室、註冊組或導師詢問；系統與時程相關問題請參考官方公告。</p><a href="mailto:tyctw.analyze@gmail.com" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-900 transition hover:bg-indigo-50"><Mail className="h-4 w-4" />聯絡我們</a></section></main>
  </div>;
}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><InfoPage /></React.StrictMode>);
